blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/formkit/formkit/discussions
    about: Have a feature request? Start a community discussion about it!
  - name: Discord community
    url: https://discord.gg/Vhu97pAC76
    about: Please ask and answer questions here.
